---
# Schuyler Dillon
# 2/2/2024
# Alpha - 2235
# Deploys a windows server
#
# This script will deploy one domain controller ready windows 2022 server 

# This sets variables and calls the 2 roles needed to create a server
- name: Install openstack.cloud collection
  hosts: localhost
  vars:
    flavorSize: large
    volumeSize: 250
    keyName: Ansible-Key
    network_id: d8dcba1c-9405-433c-a2e5-f4c205e7cade
    hostip: 192.168.100.101
    hostname: Primary_DC
    script: prepare-for-ansible-windows.ps1
    hostImage: WinSrv2022-20348-2022
  gather_facts: no
  roles:
    - { role: openstack, become: yes }
    - createHost
