---
- name: Install and configure vsftpd
  hosts: all
  become: yes
  vars:
    vsftpd_enable_service: true
    vsftpd_copy_templates: true
    vsftpd_firewall_configure: true
    vsftpd_firewall_rules:
      - service: ftp
    vsftpd_enable_selinux: true
    vsftp_selinux_booleans:
      - name: ftp_home_dir
        state: true
        persistent: true
      - name: ftpd_full_access
        state: true
        persistent: true
  tasks:
    - block:
      - name: Install vsftpd package
        apt:
          name: vsftpd
          state: present
    - block:
      - name: Add TestUser
        user:
          name: "DummyUser"
          shell: "/bin/bash"
          password: "{{ 'password' | password_hash('sha512') }}"
    - block:
      - name: Start FTP service
        become: yes
        service: name=vsftpd state=restarted enabled=yes
