---
- name: Install and Launch Apache
  become: true
  hosts: linux
  tasks:

    - name: Install Apache
      apt:
        name: apache2
        update_cache: yes
        state: latest


    - name: Start Apache
      service:
        name: apache2
        state: started
