---
# Alex Nasca
# Modified by Schuyler Dillon 
# 1/17/2024
# Active directory Domain Controller setup

# This script will deploy one domain controller ready windows 2022 server 

#Task 1: download necessary package for openstack deployment
- name: Install openstack.cloud collection
  hosts: localhost
  gather_facts: no
  become: true
  roles:
    - openstack


# Task 2: create instance and connect to network
- name: Install openstack.cloud collection
  hosts: localhost
  vars:
    network_id: d8dcba1c-9405-433c-a2e5-f4c205e7cade
    DC_ip: 192.168.100.101
    DC_name: Primary_DC
    script: prepare-for-ansible-windows.ps1
  gather_facts: no

  tasks:
    - name: Create instance of Windows Server 2022 
    #will simply use the cli command rather than the module because the module is buggy
      command: >
        openstack server create
        --flavor large
        --image WinSrv2022-20348-2022
        --boot-from-volume 250
        --user-data ./prepare-for-ansible-windows.ps1
        --nic net-id={{ network_id }},v4-fixed-ip={{ DC_ip }}
        --key-name Ansible-Key
        {{ DC_name }}
      ignore_errors: no
