- name: Execute OpenStack CLI to Create Instance 
  shell: >
    openstack server create {{ box_name }} 
    --flavor {{ flavor }}
    --image {{ image }}
    --boot-from-volume {{ boot_from_volume }}
    --nic net-id={{ network_id }},v4-fixed-ip={{ box_ip }}
    --key-name {{ ssh_key }}
