---
# tasks file for changePassword
  - name: Create several users
    ansible.windows.win_user:
      name: "{{ item }}"
      password: P@ssword123
      state: present
      groups:
        - Users
        - Domain Users    
    ignore_errors: true
    loop:
      - VanHalen
      - Metallica
      - BonJovi
      - Beatles
      - Abba
      - NeilDiamond
      - Madonna
      - Nena
      - Prince
      - MJ
      - Gaga
      - Beyonce
