---
# tasks file for create_ssh_key

- name: Get Exisiting Keys
  shell: "openstack keypair list"
  register: keys

- name: Create SSH Keys
  shell: "openstack keypair create {{ ssh_key_name }}"
  when: ssh_key_name not in keys.stdout
